exclude = [
    ".git",
    ".pytest_cache",
    ".ruff_cache",
    ".vscode",
    "__pycache__",
    ".venv",
]

line-length = 88
indent-width = 4
target-version = "py312"

[lint]
select = ["ALL"]
ignore = [
    "COM812",
    "COM819",
    "D100",
    "D104",
    "D203",
    "D213",
    "D300",
    "E111",
    "E114",
    "E117",
    "ISC001",
    "ISC002",
    "Q000",
    "Q001",
    "Q002",
    "Q003",
    "W191",
    "EXE002",
]
fixable = ["ALL"]
unfixable = []
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[lint.pydocstyle]
convention = "google"

[lint.extend-per-file-ignores]
"tests/**/*.py" = [
    "S101",
]
"scripts/**/*.py" = [
    "INP001",
]
"shared/**/*.py" = [
    "INP001",
]
"examples/**/*.py" = [
    "INP001",
]

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
